Fix a few issues

diff --git a/templates/github/workflows/test-integration.yml b/templates/github/workflows/test-integration.yml
--- a/templates/github/workflows/test-integration.yml
+++ b/templates/github/workflows/test-integration.yml
@@ -36,8 +36,10 @@ jobs:
           tar -C ~/sdk/gotip -xzf gotip.tar.gz
           ~/sdk/gotip/bin/go version
           echo "PATH=$HOME/go/bin:$HOME/sdk/gotip/bin/:$PATH" >> $GITHUB_ENV
+
       - name: Checkout code
         uses: actions/checkout@v2
+
       - name: Go cache
         uses: actions/cache@v2
         with:
@@ -50,6 +52,7 @@ jobs:
           key: ${{ runner.os }}-go-cache-${{ hashFiles('**/go.sum') }}
           restore-keys: |
             ${{ runner.os }}-go-cache
+
       - name: Restore base test coverage
         id: base-coverage
         uses: actions/cache@v2
@@ -57,7 +60,8 @@ jobs:
           path: |
             integration-base.txt
           # Use base sha for PR or new commit hash for master/main push in test result key.
-          key: ${{ runner.os }}-integration-test-coverage-${{ (github.event.pull_request.base.sha != github.event.after) && github.event.pull_request.base.sha || github.event.after }}
+          key: ${{ runner.os }}-integration-test-base-coverage-${{ (github.event.pull_request.base.sha != github.event.after) && github.event.pull_request.base.sha || github.event.after }}
+
       - name: Checkout base code
         if: env.RUN_BASE_COVERAGE == 'on' && steps.base-coverage.outputs.cache-hit != 'true' && github.event.pull_request.base.sha != ''
         uses: actions/checkout@v2
@@ -70,24 +74,30 @@ jobs:
         if: env.RUN_BASE_COVERAGE == 'on' && steps.base-coverage.outputs.cache-hit != 'true' && github.event.pull_request.base.sha != ''
         run: |
           cd __base
-          make | grep test-integration && (make test-integration && go tool cover -func=./integration.coverprofile | sed -e 's/.go:[0-9]*:\t/.go\t/g' | sed -e 's/\t\t*/\t/g'  > ../integration-base.txt) || echo "No test-integration in base"
+          make | grep test-integration && (make test-integration && go tool cover -func=./integration.coverprofile > ../integration-base.txt) || echo "No test-integration in base"
+
       - name: Test
         id: test
         run: |
           make test-integration
-          go tool cover -func=./integration.coverprofile | sed -e 's/.go:[0-9]*:\t/.go\t/g' | sed -e 's/\t\t*/\t/g'  > integration.txt
+          go tool cover -func=./integration.coverprofile > integration.txt
+          TOTAL=$(grep 'total:' integration.txt)
+          echo "${TOTAL}"
+          echo "::set-output name=total::$TOTAL"
 
       - name: Annotate missing test coverage
         id: annotate
         if: github.event.pull_request.base.sha != ''
         run: |
           git fetch origin master ${{ github.event.pull_request.base.sha }}
-          curl -sLO https://github.com/vearutop/gocovdiff/releases/download/v1.3.0/linux_amd64.tar.gz && tar xf linux_amd64.tar.gz && echo "c5fa13a6bce4e2c1960941f13e32429d8e05c909d4a08e41c46b83b72b162374  gocovdiff" | shasum -c
+          curl -sLO https://github.com/vearutop/gocovdiff/releases/download/v1.3.2/linux_amd64.tar.gz && tar xf linux_amd64.tar.gz && echo "78146b31ec37ac8037a25d33b0f3c70c85adb0f8b682441b04b3daa518eaa489  gocovdiff" | shasum -c
           REP=$(./gocovdiff -cov integration.coverprofile -gha-annotations gha-integration.txt -delta-cov-file delta-cov-integration.txt -target-delta-cov ${TARGET_DELTA_COV})
           echo "${REP}"
           REP="${REP//$'\n'/%0A}"
           cat gha-integration.txt
-          DIFF=$(test -e integration-base.txt && (gocovdiff -func-cov integration.txt -func-base-cov integration-base.txt) || echo "Missing base coverage file")
+          test -e integration-base.txt && cat integration-base.txt
+          DIFF=$(test -e integration-base.txt && ./gocovdiff -func-cov integration.txt -func-base-cov integration-base.txt || echo "Missing base coverage file")
+          DIFF="${DIFF//$'\n'/%0A}"
           TOTAL=$(cat delta-cov-integration.txt)
           echo "::set-output name=rep::$REP"
           echo "::set-output name=diff::$DIFF"
@@ -112,9 +122,8 @@ jobs:
 
             <details><summary>Coverage diff with base branch</summary>
 
-            ```diff
             ${{ steps.annotate.outputs.diff }}
-            ```
+            
             </details>
 
       - name: Store base coverage
